export { ProductDetailPage } from './components/ProductDetailPage'
export { ProductHero } from './components/ProductHero'
export { ProductInfoSections } from './components/ProductInfoSections'
export { ProductNutrientTable } from './components/ProductNutrientTable'
export { ProductScoreBadges } from './components/ProductScoreBadges'
export { ProductServingNote } from './components/ProductServingNote'
export { ProductSheet } from './components/ProductSheet'
export type { ProductInfo } from './services/product'
export { lookupByBarcode } from './services/product'
